server:
  port: 8083
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka,http://127.0.0.1:8081/eureka


spring:
  application:
    name: api

feign:
  hystrix:
    enabled: false
  okhttp:
    enabled: true

